### ISSUE TITLE
Timeline for Express Checkout

### ISSUE THREAD

**Issue by andriokha** [afterpay/sdk-php#10]
Hi, thanks for providing this project publicly!

I saw there's a branch `feature/express-checkout` but it looks like it doesn't have any changes in it yet. I was just wondering whether work had started and if there was a _rough_ idea when Express Checkout might be usable?

Thanks again!

**Comment by benfterpay** [comment]
Hi @andriokha,

Thank you for your question, and for your patience.

These works are now being prioritised. There are about 4 main components to this update. Progress has been made on the first one here:
https://github.com/afterpay/sdk-php/commit/c8071cd3f6b7fbd9cbc5056b398013c82d80f199

Current plan is to have all of the changes merged into `master` by end of June, 2021.

Please refer to this resource for an introduction to the technical integration requirements:
- https://developers.afterpay.com/afterpay-online/reference#what-is-express-checkout

Thanks again.

**Comment by andriokha** [comment]
Thanks @benfterpay!
