### ISSUE TITLE
Passing orderId in DeferredPaymentCapture constructor causes curl warning

### ISSUE THREAD

**Issue by andriokha** [afterpay/sdk-php#11]
Hi,

Thanks again for your work on this project! I don't know if I'm doing anything wrong, but I'm seeing a curl warning show up if I use the following code:

```php
$request = new DeferredPaymentCapture([
  'orderId' => $order_id,
  'requestId' => $request_id,
  'merchantReference' => $merchant_reference,
  'amount' => $amount,
]);
```
...
```
Warning: curl_setopt() expects parameter 1 to be resource, null given in Afterpay\SDK\HTTP\Request->setUri() (line 286 of /var/www/html/env/vendor/afterpay-global/afterpay-sdk-php/src/HTTP/Request.php).
Afterpay\SDK\HTTP\Request->setUri('/v2/payments/*/capture') (Line: 95)
Afterpay\SDK\HTTP\Request\DeferredPaymentCapture->setOrderId('*') (Line: 221)
Afterpay\SDK\HTTP\Request->passConstructArgsToMagicSetters(Array) (Line: 88)
Afterpay\SDK\HTTP\Request->__construct(Array) (Line: 70)
Afterpay\SDK\HTTP\Request\DeferredPaymentCapture->__construct(Array) (Line: 201)
```
And the same sort of thing when voiding a payment. It seems to be because `curl_init()` is called after constructor args are passed to magic setters:
```php
if (count($args) == 1 && $args[ 0 ] instanceof MerchantAccount) {
    $this->merchant = $args[ 0 ];
} elseif (count($args) > 0) {
    $this->passConstructArgsToMagicSetters(... $args);
}

$this->ch = curl_init();
```
 which in the case of `orderId` causes the uri to be set, which involves setting a curl option and bang.

For now I'm just doing:
```php
    $request = new DeferredPaymentCapture($other_details);
    $request->setOrderId($order_id);
```

Thanks!

**Comment by benfterpay** [comment]
Hi @andriokha,

Thanks for taking the time to describe this behaviour in detail.

The request constructor is designed to accept _body parameters_ in various formats. The `orderId` however is a _path parameter_ (e.g. `/v2/payments/{orderId}/void`).

The differences may become a little more apparent by analysing this file:

https://github.com/afterpay/sdk-php/blob/master/src/HTTP/Request/DeferredPaymentCapture.php

Admittedly, the distinction could be made clearer. Accepting both path and body params together in the class constructor could also be considered.

For the time being, please accept the explanation above. Thank you.

**Comment by andriokha** [comment]
> The request constructor is designed to accept body parameters in various formats

The missing piece of the puzzle! Perfect, thanks @benfterpay!
