### ISSUE TITLE
Email addresses longer than 45 characters

### ISSUE THREAD

**Issue by remcotolsma** [afterpay/sdk-php#15]
Hi, I had already sent a message via https://www.afterpay.nl/nl/vragen/contact/, but this way we might reach a developer faster. On https://mip.afterpay.nl/en/api-documentation/ I read that an e-mail address cannot be longer than 45 characters (Max 45 characters). However, an email address can be much longer, for example: administratie@rozendaal-installatietechniek.nl. The Rabobbank OmniKassa solution appears to have taken over the 45-character limit from you. It would be nice if you allowed email addresses with 320 characters, according to RFC 3696:

> In addition to restrictions on syntax, there is a length limit on email addresses. That limit is a maximum of 64 characters (octets) in the "local part" (before the "@") and a maximum of 255 characters (octets) in the domain part (after the "@") for a total length of 320 characters. Systems that handle email should be prepared to process addresses which are that long, even though they are rarely encountered.

**Source:** https://tools.ietf.org/html/rfc3696#section-3

https://github.com/wp-pay-gateways/omnikassa-2/issues/9

**Comment by benfterpay** [comment]
Hi @remcotolsma,

This repository belongs to [afterpay.com](https://www.afterpay.com/). There is no affiliation with the "AfterPay" entity in the Netherlands, or the Arvato Finance B.V. organisation.

Thank you.
